package com.example.collectingdialect.ui.collecting

import android.content.Context
import androidx.databinding.Bindable
import com.example.collectingdialect.data.SpeakerInfo
import com.example.collectingdialect.ui.BaseViewModel
import com.example.collectingdialect.ui.MainActivity

open class InfoViewModel: BaseViewModel() {
    companion object {
        const val KEY_ID = "id"
        const val KEY_GENDER = "gender"
        const val KEY_BIRTH_YEAR = "birth_year"
        const val KEY_RESIDENCE_PROVINCE = "residence_province"
        const val KEY_RESIDENCE_CITY = "residence_city"
        const val KEY_RESIDENCE_PERIOD = "residence_period"
        const val KEY_JOB = "job"
        const val KEY_ACADEMIC_BACKGROUND = "academic_background"
        const val KEY_HEALTH_CONDITION = "health_condition"

        const val GENDER_MALE_STRING = "남성"
        const val GENDER_FEMALE_STRING = "여성"

        const val GENDER_UNKNOWN = "u"
        const val GENDER_MALE = "m"
        const val GENDER_FEMALE = "f"

        const val RESIDENCE_PROVINCE_GANGWON_STRING = "강원도"
        const val RESIDENCE_PROVINCE_CHUNGCHEONG_STRING = "충청도"
        const val RESIDENCE_PROVINCE_GYEONGSANG_STRING = "경상도"
        const val RESIDENCE_PROVINCE_JEONRA_STRING = "전라도"
        const val RESIDENCE_PROVINCE_JEJU_STRING = "제주도"

        const val RESIDENCE_PROVINCE_UNKNOWN = "un"
        const val RESIDENCE_PROVINCE_GANGWON = "gw"
        const val RESIDENCE_PROVINCE_CHUNGCHEONG = "cc"
        const val RESIDENCE_PROVINCE_GYEONGSANG = "gs"
        const val RESIDENCE_PROVINCE_JEONRA = "jl"
        const val RESIDENCE_PROVINCE_JEJU = "jj"

        const val RESIDENCE_CITY_UNKNOWN = 0

        const val RESIDENCE_CITY_GANGWON_GANGNEUNG_STRING = "강릉"
        const val RESIDENCE_CITY_GANGWON_GOSEONG_STRING = "고성"
        const val RESIDENCE_CITY_GANGWON_DONGHAE_STRING = "동해"
        const val RESIDENCE_CITY_GANGWON_SOKCHO_STRING = "속초"
        const val RESIDENCE_CITY_GANGWON_SAMCHEOK_STRING = "삼척"
        const val RESIDENCE_CITY_GANGWON_WONJU_STRING = "원주"
        const val RESIDENCE_CITY_GANGWON_YEONGWOL_STRING = "영월"
        const val RESIDENCE_CITY_GANGWON_YANGGU_STRING = "양구"
        const val RESIDENCE_CITY_GANGWON_YANGYANG_STRING = "양양"
        const val RESIDENCE_CITY_GANGWON_INJE_STRING = "인제"
        const val RESIDENCE_CITY_GANGWON_JEONGSEON_STRING = "정선"
        const val RESIDENCE_CITY_GANGWON_CHEOLWON_STRING = "철원"
        const val RESIDENCE_CITY_GANGWON_CHUNCHEON_STRING = "춘천"
        const val RESIDENCE_CITY_GANGWON_TAEBAEK_STRING = "태백"
        const val RESIDENCE_CITY_GANGWON_PYEONGCHANG_STRING = "평창"
        const val RESIDENCE_CITY_GANGWON_HWACHEON_STRING = "화천"
        const val RESIDENCE_CITY_GANGWON_HONGCHEON_STRING = "홍천"
        const val RESIDENCE_CITY_GANGWON_HOENGSEONG_STRING = "횡성"

        const val RESIDENCE_CITY_GANGWON_GANGNEUNG = 1
        const val RESIDENCE_CITY_GANGWON_GOSEONG = 2
        const val RESIDENCE_CITY_GANGWON_DONGHAE = 3
        const val RESIDENCE_CITY_GANGWON_SOKCHO = 4
        const val RESIDENCE_CITY_GANGWON_SAMCHEOK = 5
        const val RESIDENCE_CITY_GANGWON_WONJU = 6
        const val RESIDENCE_CITY_GANGWON_YEONGWOL = 7
        const val RESIDENCE_CITY_GANGWON_YANGGU = 8
        const val RESIDENCE_CITY_GANGWON_YANGYANG = 9
        const val RESIDENCE_CITY_GANGWON_INJE = 10
        const val RESIDENCE_CITY_GANGWON_JEONGSEON = 11
        const val RESIDENCE_CITY_GANGWON_CHEOLWON = 12
        const val RESIDENCE_CITY_GANGWON_CHUNCHEON = 13
        const val RESIDENCE_CITY_GANGWON_TAEBAEK = 14
        const val RESIDENCE_CITY_GANGWON_PYEONGCHANG = 15
        const val RESIDENCE_CITY_GANGWON_HWACHEON = 16
        const val RESIDENCE_CITY_GANGWON_HONGCHEON = 17
        const val RESIDENCE_CITY_GANGWON_HOENGSEONG = 18

        const val RESIDENCE_CITY_GYEONGSANG_DAEGU_STRING = "대구"
        const val RESIDENCE_CITY_GYEONGSANG_BUSAN_STRING = "부산"
        const val RESIDENCE_CITY_GYEONGSANG_ULSAN_STRING = "울산"
        const val RESIDENCE_CITY_GYEONGSANG_GYEONGSAN_STRING = "경산"
        const val RESIDENCE_CITY_GYEONGSANG_GYEONGJU_STRING = "경주"
        const val RESIDENCE_CITY_GYEONGSANG_GEOJE_STRING = "거제"
        const val RESIDENCE_CITY_GYEONGSANG_GUMI_STRING = "구미"
        const val RESIDENCE_CITY_GYEONGSANG_GIMHAE_STRING = "김해"
        const val RESIDENCE_CITY_GYEONGSANG_GIMCHEON_STRING = "김천"
        const val RESIDENCE_CITY_GYEONGSANG_GEOCHANG_STRING = "거창"
        const val RESIDENCE_CITY_GYEONGSANG_GORYEONG_STRING = "고령"
        const val RESIDENCE_CITY_GYEONGSANG_GOSEONG_STRING = "고성 "
        const val RESIDENCE_CITY_GYEONGSANG_GUNWI_STRING = "군위"
        const val RESIDENCE_CITY_GYEONGSANG_NAMHAE_STRING = "남해"
        const val RESIDENCE_CITY_GYEONGSANG_MUNGYEONG_STRING = "문경"
        const val RESIDENCE_CITY_GYEONGSANG_MIRYANG_STRING = "밀양"
        const val RESIDENCE_CITY_GYEONGSANG_BONGHWA_STRING = "봉화"
        const val RESIDENCE_CITY_GYEONGSANG_SACHEON_STRING = "사천"
        const val RESIDENCE_CITY_GYEONGSANG_SANCHEONG_STRING = "산청"
        const val RESIDENCE_CITY_GYEONGSANG_SANGJU_STRING = "상주"
        const val RESIDENCE_CITY_GYEONGSANG_SEONGJU_STRING = "성주"
        const val RESIDENCE_CITY_GYEONGSANG_ANDONG_STRING = "안동"
        const val RESIDENCE_CITY_GYEONGSANG_YEONGCHEON_STRING = "영천"
        const val RESIDENCE_CITY_GYEONGSANG_UISEONG_STRING = "의성"
        const val RESIDENCE_CITY_GYEONGSANG_YEONGJU_STRING = "영주"
        const val RESIDENCE_CITY_GYEONGSANG_YEONGYANG_STRING = "영양"
        const val RESIDENCE_CITY_GYEONGSANG_YEONGDEOK_STRING = "영덕"
        const val RESIDENCE_CITY_GYEONGSANG_YECHEON_STRING = "예천"
        const val RESIDENCE_CITY_GYEONGSANG_ULJIN_STRING = "울진"
        const val RESIDENCE_CITY_GYEONGSANG_ULLEUNG_STRING = "울릉"
        const val RESIDENCE_CITY_GYEONGSANG_YANGSAN_STRING = "양산"
        const val RESIDENCE_CITY_GYEONGSANG_UIRYEONG_STRING = "의령"
        const val RESIDENCE_CITY_GYEONGSANG_JINJU_STRING = "진주"
        const val RESIDENCE_CITY_GYEONGSANG_CHANGWON_STRING = "창원"
        const val RESIDENCE_CITY_GYEONGSANG_CHANGNYEONG_STRING = "창녕"
        const val RESIDENCE_CITY_GYEONGSANG_CHEONGSONG_STRING = "청송"
        const val RESIDENCE_CITY_GYEONGSANG_CHEONGDO_STRING = "청도"
        const val RESIDENCE_CITY_GYEONGSANG_CHILGOK_STRING = "칠곡"
        const val RESIDENCE_CITY_GYEONGSANG_TONGYEONG_STRING = "통영"
        const val RESIDENCE_CITY_GYEONGSANG_POHANG_STRING = "포항"
        const val RESIDENCE_CITY_GYEONGSANG_HAPCHEON_STRING = "합천"
        const val RESIDENCE_CITY_GYEONGSANG_HAMAN_STRING = "함안"
        const val RESIDENCE_CITY_GYEONGSANG_HAMYANG_STRING = "함양"
        const val RESIDENCE_CITY_GYEONGSANG_HADONG_STRING = "하동"

        const val RESIDENCE_CITY_GYEONGSANG_DAEGU = 19
        const val RESIDENCE_CITY_GYEONGSANG_BUSAN = 20
        const val RESIDENCE_CITY_GYEONGSANG_ULSAN = 21
        const val RESIDENCE_CITY_GYEONGSANG_GYEONGSAN = 22
        const val RESIDENCE_CITY_GYEONGSANG_GYEONGJU = 23
        const val RESIDENCE_CITY_GYEONGSANG_GEOJE = 24
        const val RESIDENCE_CITY_GYEONGSANG_GUMI = 25
        const val RESIDENCE_CITY_GYEONGSANG_GIMHAE = 26
        const val RESIDENCE_CITY_GYEONGSANG_GIMCHEON = 27
        const val RESIDENCE_CITY_GYEONGSANG_GEOCHANG = 28
        const val RESIDENCE_CITY_GYEONGSANG_GORYEONG = 29
        const val RESIDENCE_CITY_GYEONGSANG_GOSEONG = 30
        const val RESIDENCE_CITY_GYEONGSANG_GUNWI = 31
        const val RESIDENCE_CITY_GYEONGSANG_NAMHAE = 32
        const val RESIDENCE_CITY_GYEONGSANG_MUNGYEONG = 33
        const val RESIDENCE_CITY_GYEONGSANG_MIRYANG = 34
        const val RESIDENCE_CITY_GYEONGSANG_BONGHWA = 35
        const val RESIDENCE_CITY_GYEONGSANG_SACHEON = 36
        const val RESIDENCE_CITY_GYEONGSANG_SANCHEONG = 37
        const val RESIDENCE_CITY_GYEONGSANG_SANGJU = 38
        const val RESIDENCE_CITY_GYEONGSANG_SEONGJU = 39
        const val RESIDENCE_CITY_GYEONGSANG_ANDONG = 40
        const val RESIDENCE_CITY_GYEONGSANG_YEONGCHEON = 41
        const val RESIDENCE_CITY_GYEONGSANG_UISEONG = 42
        const val RESIDENCE_CITY_GYEONGSANG_YEONGJU = 43
        const val RESIDENCE_CITY_GYEONGSANG_YEONGYANG = 44
        const val RESIDENCE_CITY_GYEONGSANG_YEONGDEOK = 45
        const val RESIDENCE_CITY_GYEONGSANG_YECHEON = 46
        const val RESIDENCE_CITY_GYEONGSANG_ULJIN = 47
        const val RESIDENCE_CITY_GYEONGSANG_ULLEUNG = 48
        const val RESIDENCE_CITY_GYEONGSANG_YANGSAN = 49
        const val RESIDENCE_CITY_GYEONGSANG_UIRYEONG = 50
        const val RESIDENCE_CITY_GYEONGSANG_JINJU = 51
        const val RESIDENCE_CITY_GYEONGSANG_CHANGWON = 52
        const val RESIDENCE_CITY_GYEONGSANG_CHANGNYEONG = 53
        const val RESIDENCE_CITY_GYEONGSANG_CHEONGSONG = 54
        const val RESIDENCE_CITY_GYEONGSANG_CHEONGDO = 55
        const val RESIDENCE_CITY_GYEONGSANG_CHILGOK = 56
        const val RESIDENCE_CITY_GYEONGSANG_TONGYEONG = 57
        const val RESIDENCE_CITY_GYEONGSANG_POHANG = 58
        const val RESIDENCE_CITY_GYEONGSANG_HAPCHEON = 59
        const val RESIDENCE_CITY_GYEONGSANG_HAMAN = 60
        const val RESIDENCE_CITY_GYEONGSANG_HAMYANG = 61
        const val RESIDENCE_CITY_GYEONGSANG_HADONG = 62

        const val RESIDENCE_CITY_JEONRA_GWANGJU_STRING = "광주"
        const val RESIDENCE_CITY_JEONRA_GOCHANG_STRING = "고창"
        const val RESIDENCE_CITY_JEONRA_GOKSEONG_STRING = "곡성"
        const val RESIDENCE_CITY_JEONRA_GOHEUNG_STRING = "고흥"
        const val RESIDENCE_CITY_JEONRA_GURYE_STRING = "구례"
        const val RESIDENCE_CITY_JEONRA_GANGJIN_STRING = "강진"
        const val RESIDENCE_CITY_JEONRA_GUNSAN_STRING = "군산"
        const val RESIDENCE_CITY_JEONRA_GIMJE_STRING = "김제"
        const val RESIDENCE_CITY_JEONRA_GWANGYANG_STRING = "광양"
        const val RESIDENCE_CITY_JEONRA_NAJU_STRING = "나주"
        const val RESIDENCE_CITY_JEONRA_NAMWON_STRING = "남원"
        const val RESIDENCE_CITY_JEONRA_DAMYANG_STRING = "담양"
        const val RESIDENCE_CITY_JEONRA_MOKPO_STRING = "목포"
        const val RESIDENCE_CITY_JEONRA_MUAN_STRING = "무안"
        const val RESIDENCE_CITY_JEONRA_MUJU_STRING = "무주"
        const val RESIDENCE_CITY_JEONRA_BOSEONG_STRING = "보성"
        const val RESIDENCE_CITY_JEONRA_BUAN_STRING = "부안"
        const val RESIDENCE_CITY_JEONRA_SHINAN_STRING = "신안"
        const val RESIDENCE_CITY_JEONRA_SUNCHEON_STRING = "순천"
        const val RESIDENCE_CITY_JEONRA_SUNCHANG_STRING = "순창"
        const val RESIDENCE_CITY_JEONRA_YEOSU_STRING = "여수"
        const val RESIDENCE_CITY_JEONRA_YEONGAM_STRING = "영암"
        const val RESIDENCE_CITY_JEONRA_YEONGGWANG_STRING = "영광"
        const val RESIDENCE_CITY_JEONRA_WANDO_STRING = "완도"
        const val RESIDENCE_CITY_JEONRA_WANJU_STRING = "완주"
        const val RESIDENCE_CITY_JEONRA_IKSAN_STRING = "익산"
        const val RESIDENCE_CITY_JEONRA_IMSIL_STRING = "임실"
        const val RESIDENCE_CITY_JEONRA_JANGSEONG_STRING = "장성"
        const val RESIDENCE_CITY_JEONRA_JANGSU_STRING = "장수"
        const val RESIDENCE_CITY_JEONRA_JEONGEUP_STRING = "정읍"
        const val RESIDENCE_CITY_JEONRA_JEONJU_STRING = "전주"
        const val RESIDENCE_CITY_JEONRA_JINAN_STRING = "진안"
        const val RESIDENCE_CITY_JEONRA_JINDO_STRING = "진도"
        const val RESIDENCE_CITY_JEONRA_JANGHEUNG_STRING = "장흥"
        const val RESIDENCE_CITY_JEONRA_HWASUN_STRING = "화순"
        const val RESIDENCE_CITY_JEONRA_HAENAM_STRING = "해남"
        const val RESIDENCE_CITY_JEONRA_HAMPYEONG_STRING = "함평"

        const val RESIDENCE_CITY_JEONRA_GWANGJU = 63
        const val RESIDENCE_CITY_JEONRA_GOCHANG = 64
        const val RESIDENCE_CITY_JEONRA_GOKSEONG = 65
        const val RESIDENCE_CITY_JEONRA_GOHEUNG = 66
        const val RESIDENCE_CITY_JEONRA_GURYE = 67
        const val RESIDENCE_CITY_JEONRA_GANGJIN = 68
        const val RESIDENCE_CITY_JEONRA_GUNSAN = 69
        const val RESIDENCE_CITY_JEONRA_GIMJE = 70
        const val RESIDENCE_CITY_JEONRA_GWANGYANG = 71
        const val RESIDENCE_CITY_JEONRA_NAJU = 72
        const val RESIDENCE_CITY_JEONRA_NAMWON = 73
        const val RESIDENCE_CITY_JEONRA_DAMYANG = 74
        const val RESIDENCE_CITY_JEONRA_MOKPO = 75
        const val RESIDENCE_CITY_JEONRA_MUAN = 76
        const val RESIDENCE_CITY_JEONRA_MUJU = 77
        const val RESIDENCE_CITY_JEONRA_BOSEONG = 78
        const val RESIDENCE_CITY_JEONRA_BUAN = 79
        const val RESIDENCE_CITY_JEONRA_SHINAN = 80
        const val RESIDENCE_CITY_JEONRA_SUNCHEON = 81
        const val RESIDENCE_CITY_JEONRA_SUNCHANG = 82
        const val RESIDENCE_CITY_JEONRA_YEOSU = 83
        const val RESIDENCE_CITY_JEONRA_YEONGAM = 84
        const val RESIDENCE_CITY_JEONRA_YEONGGWANG = 85
        const val RESIDENCE_CITY_JEONRA_WANDO = 86
        const val RESIDENCE_CITY_JEONRA_WANJU = 87
        const val RESIDENCE_CITY_JEONRA_IKSAN = 88
        const val RESIDENCE_CITY_JEONRA_IMSIL = 89
        const val RESIDENCE_CITY_JEONRA_JANGSEONG = 90
        const val RESIDENCE_CITY_JEONRA_JANGSU = 91
        const val RESIDENCE_CITY_JEONRA_JEONGEUP = 92
        const val RESIDENCE_CITY_JEONRA_JEONJU = 93
        const val RESIDENCE_CITY_JEONRA_JINAN = 94
        const val RESIDENCE_CITY_JEONRA_JINDO = 95
        const val RESIDENCE_CITY_JEONRA_JANGHEUNG = 96
        const val RESIDENCE_CITY_JEONRA_HWASUN = 97
        const val RESIDENCE_CITY_JEONRA_HAENAM = 98
        const val RESIDENCE_CITY_JEONRA_HAMPYEONG = 99

        const val RESIDENCE_CITY_CHUNGCHEONG_DAEJEON_STRING = "대전"
        const val RESIDENCE_CITY_CHUNGCHEONG_SEJONG_STRING = "세종"
        const val RESIDENCE_CITY_CHUNGCHEONG_GONGJU_STRING = "공주"
        const val RESIDENCE_CITY_CHUNGCHEONG_GEUMSAN_STRING = "금산"
        const val RESIDENCE_CITY_CHUNGCHEONG_GOESAN_STRING = "괴산"
        const val RESIDENCE_CITY_CHUNGCHEONG_GYERYONG_STRING = "계룡"
        const val RESIDENCE_CITY_CHUNGCHEONG_NONSAN_STRING = "논산"
        const val RESIDENCE_CITY_CHUNGCHEONG_DANGJIN_STRING = "당진"
        const val RESIDENCE_CITY_CHUNGCHEONG_DANYANG_STRING = "단양"
        const val RESIDENCE_CITY_CHUNGCHEONG_BORYEONG_STRING = "보령"
        const val RESIDENCE_CITY_CHUNGCHEONG_BUYEO_STRING = "부여"
        const val RESIDENCE_CITY_CHUNGCHEONG_BOEUN_STRING = "보은"
        const val RESIDENCE_CITY_CHUNGCHEONG_SEOSAN_STRING = "서산"
        const val RESIDENCE_CITY_CHUNGCHEONG_SEOCHEON_STRING = "서천"
        const val RESIDENCE_CITY_CHUNGCHEONG_YEONGDONG_STRING = "영동"
        const val RESIDENCE_CITY_CHUNGCHEONG_OKCHEON_STRING = "옥천"
        const val RESIDENCE_CITY_CHUNGCHEONG_EUMSEONG_STRING = "음성"
        const val RESIDENCE_CITY_CHUNGCHEONG_YESAN_STRING = "예산"
        const val RESIDENCE_CITY_CHUNGCHEONG_ASAN_STRING = "아산"
        const val RESIDENCE_CITY_CHUNGCHEONG_JECHEON_STRING = "제천"
        const val RESIDENCE_CITY_CHUNGCHEONG_JEUNGPYEONG_STRING = "증평"
        const val RESIDENCE_CITY_CHUNGCHEONG_JINCHEON_STRING = "진천"
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONGJU_STRING = "청주"
        const val RESIDENCE_CITY_CHUNGCHEONG_CHUNGJU_STRING = "충주"
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONAN_STRING = "천안"
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONGYANG_STRING = "청양"
        const val RESIDENCE_CITY_CHUNGCHEONG_TAEAN_STRING = "태안"
        const val RESIDENCE_CITY_CHUNGCHEONG_HONGSEONG_STRING = "홍성"

        const val RESIDENCE_CITY_CHUNGCHEONG_DAEJEON = 100
        const val RESIDENCE_CITY_CHUNGCHEONG_SEJONG = 101
        const val RESIDENCE_CITY_CHUNGCHEONG_GONGJU = 102
        const val RESIDENCE_CITY_CHUNGCHEONG_GEUMSAN = 103
        const val RESIDENCE_CITY_CHUNGCHEONG_GOESAN = 104
        const val RESIDENCE_CITY_CHUNGCHEONG_GYERYONG = 105
        const val RESIDENCE_CITY_CHUNGCHEONG_NONSAN = 106
        const val RESIDENCE_CITY_CHUNGCHEONG_DANGJIN = 107
        const val RESIDENCE_CITY_CHUNGCHEONG_DANYANG = 108
        const val RESIDENCE_CITY_CHUNGCHEONG_BORYEONG = 109
        const val RESIDENCE_CITY_CHUNGCHEONG_BUYEO = 110
        const val RESIDENCE_CITY_CHUNGCHEONG_BOEUN = 111
        const val RESIDENCE_CITY_CHUNGCHEONG_SEOSAN = 112
        const val RESIDENCE_CITY_CHUNGCHEONG_SEOCHEON = 113
        const val RESIDENCE_CITY_CHUNGCHEONG_YEONGDONG = 114
        const val RESIDENCE_CITY_CHUNGCHEONG_OKCHEON = 115
        const val RESIDENCE_CITY_CHUNGCHEONG_EUMSEONG = 116
        const val RESIDENCE_CITY_CHUNGCHEONG_YESAN = 117
        const val RESIDENCE_CITY_CHUNGCHEONG_ASAN = 118
        const val RESIDENCE_CITY_CHUNGCHEONG_JECHEON = 119
        const val RESIDENCE_CITY_CHUNGCHEONG_JEUNGPYEONG = 120
        const val RESIDENCE_CITY_CHUNGCHEONG_JINCHEON = 121
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONGJU = 122
        const val RESIDENCE_CITY_CHUNGCHEONG_CHUNGJU = 123
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONAN = 124
        const val RESIDENCE_CITY_CHUNGCHEONG_CHEONGYANG = 125
        const val RESIDENCE_CITY_CHUNGCHEONG_TAEAN = 126
        const val RESIDENCE_CITY_CHUNGCHEONG_HONGSEONG = 127


        const val RESIDENCE_CITY_JEJU_JEJU_STRING = "제주"
        const val RESIDENCE_CITY_JEJU_SEOGWIPO_STRING = "서귀포"

        const val RESIDENCE_CITY_JEJU_JEJU = 128
        const val RESIDENCE_CITY_JEJU_SEOGWIPO = 129

        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_ELEMENTARY_SCHOOL_STRING = "초졸이하"
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_MIDDLE_SCHOOL_STRING = "중졸이하"
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_HIGH_SCHOOL_STRING = "고졸이하"
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_GRAD_SCHOOL_STRING = "대학원이하"

        const val ACADEMIC_BACKGROUND_UNKNOWN = 0
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_ELEMENTARY_SCHOOL = 1
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_MIDDLE_SCHOOL = 2
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_HIGH_SCHOOL = 3
        const val ACADEMIC_BACKGROUND_GRADUATED_UNDER_GRAD_SCHOOL = 4

        const val HEALTH_CONDITION_CLEAR_STRING = "무"
        const val HEALTH_CONDITION_LOSS_OF_TEETH_STRING = "치아손실"
        const val HEALTH_CONDITION_ARTICULATION_DISORDER_STRING = "조음장애"
        const val HEALTH_CONDITION_BOTH_STRING = "치아손실, 조음장애"

        const val HEALTH_CONDITION_UNKNOWN = 0
        const val HEALTH_CONDITION_CLEAR = 1
        const val HEALTH_CONDITION_LOSS_OF_TEETH = 2
        const val HEALTH_CONDITION_ARTICULATION_DISORDER = 3
        const val HEALTH_CONDITION_BOTH = 4

        fun deleteInfo(speakerId: String) {
            val context = MainActivity.contextRequester?.invoke() ?: kotlin.run {
                return
            }
            val infoPreference = context.getSharedPreferences(speakerId, Context.MODE_PRIVATE)
            infoPreference.edit().clear().apply()
        }
    }

    val genderList = arrayOf(
        GENDER_MALE_STRING,
        GENDER_FEMALE_STRING
    )
        @Bindable get

    val residenceProvinceList = arrayOf(
        RESIDENCE_PROVINCE_GANGWON_STRING,
        RESIDENCE_PROVINCE_CHUNGCHEONG_STRING,
        RESIDENCE_PROVINCE_GYEONGSANG_STRING,
        RESIDENCE_PROVINCE_JEONRA_STRING,
        RESIDENCE_PROVINCE_JEJU_STRING
    )
        @Bindable get

    val cityListGangwon = arrayOf(
        RESIDENCE_CITY_GANGWON_GANGNEUNG_STRING,
        RESIDENCE_CITY_GANGWON_GOSEONG_STRING,
        RESIDENCE_CITY_GANGWON_DONGHAE_STRING,
        RESIDENCE_CITY_GANGWON_SOKCHO_STRING,
        RESIDENCE_CITY_GANGWON_SAMCHEOK_STRING,
        RESIDENCE_CITY_GANGWON_WONJU_STRING,
        RESIDENCE_CITY_GANGWON_YEONGWOL_STRING,
        RESIDENCE_CITY_GANGWON_YANGGU_STRING,
        RESIDENCE_CITY_GANGWON_YANGYANG_STRING,
        RESIDENCE_CITY_GANGWON_INJE_STRING,
        RESIDENCE_CITY_GANGWON_JEONGSEON_STRING,
        RESIDENCE_CITY_GANGWON_CHEOLWON_STRING,
        RESIDENCE_CITY_GANGWON_CHUNCHEON_STRING,
        RESIDENCE_CITY_GANGWON_TAEBAEK_STRING,
        RESIDENCE_CITY_GANGWON_PYEONGCHANG_STRING,
        RESIDENCE_CITY_GANGWON_HWACHEON_STRING,
        RESIDENCE_CITY_GANGWON_HONGCHEON_STRING,
        RESIDENCE_CITY_GANGWON_HOENGSEONG_STRING,
    )
        @Bindable get

    val cityListGyeongsang = arrayOf(
        RESIDENCE_CITY_GYEONGSANG_DAEGU_STRING,
        RESIDENCE_CITY_GYEONGSANG_BUSAN_STRING,
        RESIDENCE_CITY_GYEONGSANG_ULSAN_STRING,
        RESIDENCE_CITY_GYEONGSANG_GYEONGSAN_STRING,
        RESIDENCE_CITY_GYEONGSANG_GYEONGJU_STRING,
        RESIDENCE_CITY_GYEONGSANG_GEOJE_STRING,
        RESIDENCE_CITY_GYEONGSANG_GUMI_STRING,
        RESIDENCE_CITY_GYEONGSANG_GIMHAE_STRING,
        RESIDENCE_CITY_GYEONGSANG_GIMCHEON_STRING,
        RESIDENCE_CITY_GYEONGSANG_GEOCHANG_STRING,
        RESIDENCE_CITY_GYEONGSANG_GORYEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_GOSEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_GUNWI_STRING,
        RESIDENCE_CITY_GYEONGSANG_NAMHAE_STRING,
        RESIDENCE_CITY_GYEONGSANG_MUNGYEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_MIRYANG_STRING,
        RESIDENCE_CITY_GYEONGSANG_BONGHWA_STRING,
        RESIDENCE_CITY_GYEONGSANG_SACHEON_STRING,
        RESIDENCE_CITY_GYEONGSANG_SANCHEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_SANGJU_STRING,
        RESIDENCE_CITY_GYEONGSANG_SEONGJU_STRING,
        RESIDENCE_CITY_GYEONGSANG_ANDONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_YEONGCHEON_STRING,
        RESIDENCE_CITY_GYEONGSANG_UISEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_YEONGJU_STRING,
        RESIDENCE_CITY_GYEONGSANG_YEONGYANG_STRING,
        RESIDENCE_CITY_GYEONGSANG_YEONGDEOK_STRING,
        RESIDENCE_CITY_GYEONGSANG_YECHEON_STRING,
        RESIDENCE_CITY_GYEONGSANG_ULJIN_STRING,
        RESIDENCE_CITY_GYEONGSANG_ULLEUNG_STRING,
        RESIDENCE_CITY_GYEONGSANG_YANGSAN_STRING,
        RESIDENCE_CITY_GYEONGSANG_UIRYEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_JINJU_STRING,
        RESIDENCE_CITY_GYEONGSANG_CHANGWON_STRING,
        RESIDENCE_CITY_GYEONGSANG_CHANGNYEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_CHEONGSONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_CHEONGDO_STRING,
        RESIDENCE_CITY_GYEONGSANG_CHILGOK_STRING,
        RESIDENCE_CITY_GYEONGSANG_TONGYEONG_STRING,
        RESIDENCE_CITY_GYEONGSANG_POHANG_STRING,
        RESIDENCE_CITY_GYEONGSANG_HAPCHEON_STRING,
        RESIDENCE_CITY_GYEONGSANG_HAMAN_STRING,
        RESIDENCE_CITY_GYEONGSANG_HAMYANG_STRING,
        RESIDENCE_CITY_GYEONGSANG_HADONG_STRING,
    )
        @Bindable get

    val cityListJeonra = arrayOf(
        RESIDENCE_CITY_JEONRA_GWANGJU_STRING,
        RESIDENCE_CITY_JEONRA_GOCHANG_STRING,
        RESIDENCE_CITY_JEONRA_GOKSEONG_STRING,
        RESIDENCE_CITY_JEONRA_GOHEUNG_STRING,
        RESIDENCE_CITY_JEONRA_GURYE_STRING,
        RESIDENCE_CITY_JEONRA_GANGJIN_STRING,
        RESIDENCE_CITY_JEONRA_GUNSAN_STRING,
        RESIDENCE_CITY_JEONRA_GIMJE_STRING,
        RESIDENCE_CITY_JEONRA_GWANGYANG_STRING,
        RESIDENCE_CITY_JEONRA_NAJU_STRING,
        RESIDENCE_CITY_JEONRA_NAMWON_STRING,
        RESIDENCE_CITY_JEONRA_DAMYANG_STRING,
        RESIDENCE_CITY_JEONRA_MOKPO_STRING,
        RESIDENCE_CITY_JEONRA_MUAN_STRING,
        RESIDENCE_CITY_JEONRA_MUJU_STRING,
        RESIDENCE_CITY_JEONRA_BOSEONG_STRING,
        RESIDENCE_CITY_JEONRA_BUAN_STRING,
        RESIDENCE_CITY_JEONRA_SHINAN_STRING,
        RESIDENCE_CITY_JEONRA_SUNCHEON_STRING,
        RESIDENCE_CITY_JEONRA_SUNCHANG_STRING,
        RESIDENCE_CITY_JEONRA_YEOSU_STRING,
        RESIDENCE_CITY_JEONRA_YEONGAM_STRING,
        RESIDENCE_CITY_JEONRA_YEONGGWANG_STRING,
        RESIDENCE_CITY_JEONRA_WANDO_STRING,
        RESIDENCE_CITY_JEONRA_WANJU_STRING,
        RESIDENCE_CITY_JEONRA_IKSAN_STRING,
        RESIDENCE_CITY_JEONRA_IMSIL_STRING,
        RESIDENCE_CITY_JEONRA_JANGSEONG_STRING,
        RESIDENCE_CITY_JEONRA_JANGSU_STRING,
        RESIDENCE_CITY_JEONRA_JEONGEUP_STRING,
        RESIDENCE_CITY_JEONRA_JEONJU_STRING,
        RESIDENCE_CITY_JEONRA_JINAN_STRING,
        RESIDENCE_CITY_JEONRA_JINDO_STRING,
        RESIDENCE_CITY_JEONRA_JANGHEUNG_STRING,
        RESIDENCE_CITY_JEONRA_HWASUN_STRING,
        RESIDENCE_CITY_JEONRA_HAENAM_STRING,
        RESIDENCE_CITY_JEONRA_HAMPYEONG_STRING,
    )
        @Bindable get

    val cityListChungcheong = arrayOf(
        RESIDENCE_CITY_CHUNGCHEONG_DAEJEON_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_SEJONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_GONGJU_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_GEUMSAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_GOESAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_GYERYONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_NONSAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_DANGJIN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_DANYANG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_BORYEONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_BUYEO_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_BOEUN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_SEOSAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_SEOCHEON_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_YEONGDONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_OKCHEON_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_EUMSEONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_YESAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_ASAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_JECHEON_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_JEUNGPYEONG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_JINCHEON_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_CHEONGJU_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_CHUNGJU_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_CHEONAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_CHEONGYANG_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_TAEAN_STRING,
        RESIDENCE_CITY_CHUNGCHEONG_HONGSEONG_STRING,
    )
        @Bindable get

    val cityListJeju = arrayOf(
        RESIDENCE_CITY_JEJU_JEJU_STRING,
        RESIDENCE_CITY_JEJU_SEOGWIPO_STRING,
    )
        @Bindable get

    val academicBackgroundList = arrayOf(
        ACADEMIC_BACKGROUND_GRADUATED_UNDER_ELEMENTARY_SCHOOL_STRING,
        ACADEMIC_BACKGROUND_GRADUATED_UNDER_MIDDLE_SCHOOL_STRING,
        ACADEMIC_BACKGROUND_GRADUATED_UNDER_HIGH_SCHOOL_STRING,
        ACADEMIC_BACKGROUND_GRADUATED_UNDER_GRAD_SCHOOL_STRING,
    )
        @Bindable get

    val healthConditionList = arrayOf(
        HEALTH_CONDITION_CLEAR_STRING,
        HEALTH_CONDITION_LOSS_OF_TEETH_STRING,
        HEALTH_CONDITION_ARTICULATION_DISORDER_STRING,
        HEALTH_CONDITION_BOTH_STRING,
    )
        @Bindable get

    fun saveInfo(context: Context, speakerInfo: SpeakerInfo) {
        val infoPreference = context.getSharedPreferences(speakerInfo.speakerId, Context.MODE_PRIVATE)
        infoPreference.edit()
            .putString(KEY_GENDER, speakerInfo.gender)
            .putInt(KEY_BIRTH_YEAR, speakerInfo.birthYear)
            .putString(KEY_RESIDENCE_PROVINCE, speakerInfo.residenceProvince)
            .putString(KEY_RESIDENCE_CITY, speakerInfo.residenceCity)
            .putInt(KEY_RESIDENCE_PERIOD, speakerInfo.residencePeriod)
            .putString(KEY_JOB, speakerInfo.job)
            .putString(KEY_ACADEMIC_BACKGROUND, speakerInfo.academicBackground)
            .putString(KEY_HEALTH_CONDITION, speakerInfo.healthCondition)
            .apply()
    }

    fun loadInfo(context: Context, speakerId: String): SpeakerInfo? {
        val infoPreference = context.getSharedPreferences(speakerId, Context.MODE_PRIVATE)
        val gender = infoPreference.getString(KEY_GENDER, "") ?: ""
        val birthYear = infoPreference.getInt(KEY_BIRTH_YEAR, 0)
        val residenceProvince = infoPreference.getString(KEY_RESIDENCE_PROVINCE, "") ?: ""
        val residenceCity = infoPreference.getString(KEY_RESIDENCE_CITY, "") ?: ""
        val residencePeriod = infoPreference.getInt(KEY_RESIDENCE_PERIOD, 0)
        val job = infoPreference.getString(KEY_JOB, "") ?: ""
        val academicBackground = infoPreference.getString(KEY_ACADEMIC_BACKGROUND, "") ?: ""
        val healthCondition = infoPreference.getString(KEY_HEALTH_CONDITION, "") ?: ""
        if(gender.isEmpty() || birthYear == 0 || residenceProvince.isEmpty() || residenceCity.isEmpty() || residencePeriod == 0) {
            return null
        }
        return SpeakerInfo(
            speakerId,
            gender,
            birthYear,
            residenceProvince,
            residenceCity,
            residencePeriod,
            job,
            academicBackground,
            healthCondition
        )
    }

    fun genderValueOf(gender: String): String {
        return when(gender) {
            GENDER_MALE_STRING -> GENDER_MALE
            GENDER_FEMALE_STRING -> GENDER_FEMALE
            else -> GENDER_UNKNOWN
        }
    }

    fun residenceProvinceValueOf(residenceProvince: String): String {
        return when(residenceProvince) {
            RESIDENCE_PROVINCE_GANGWON_STRING -> RESIDENCE_PROVINCE_GANGWON
            RESIDENCE_PROVINCE_CHUNGCHEONG_STRING -> RESIDENCE_PROVINCE_CHUNGCHEONG
            RESIDENCE_PROVINCE_GYEONGSANG_STRING -> RESIDENCE_PROVINCE_GYEONGSANG
            RESIDENCE_PROVINCE_JEONRA_STRING -> RESIDENCE_PROVINCE_JEONRA
            RESIDENCE_PROVINCE_JEJU_STRING -> RESIDENCE_PROVINCE_JEJU
            else -> RESIDENCE_PROVINCE_UNKNOWN
        }
    }

    fun residenceCityValueOf(residenceCity: String): Int {
        return when(residenceCity) {
            RESIDENCE_CITY_GANGWON_GANGNEUNG_STRING -> RESIDENCE_CITY_GANGWON_GANGNEUNG
            RESIDENCE_CITY_GANGWON_GOSEONG_STRING -> RESIDENCE_CITY_GANGWON_GOSEONG
            RESIDENCE_CITY_GANGWON_DONGHAE_STRING -> RESIDENCE_CITY_GANGWON_DONGHAE
            RESIDENCE_CITY_GANGWON_SOKCHO_STRING -> RESIDENCE_CITY_GANGWON_SOKCHO
            RESIDENCE_CITY_GANGWON_SAMCHEOK_STRING -> RESIDENCE_CITY_GANGWON_SAMCHEOK
            RESIDENCE_CITY_GANGWON_WONJU_STRING -> RESIDENCE_CITY_GANGWON_WONJU
            RESIDENCE_CITY_GANGWON_YEONGWOL_STRING -> RESIDENCE_CITY_GANGWON_YEONGWOL
            RESIDENCE_CITY_GANGWON_YANGGU_STRING -> RESIDENCE_CITY_GANGWON_YANGGU
            RESIDENCE_CITY_GANGWON_YANGYANG_STRING -> RESIDENCE_CITY_GANGWON_YANGYANG
            RESIDENCE_CITY_GANGWON_INJE_STRING -> RESIDENCE_CITY_GANGWON_INJE
            RESIDENCE_CITY_GANGWON_JEONGSEON_STRING -> RESIDENCE_CITY_GANGWON_JEONGSEON
            RESIDENCE_CITY_GANGWON_CHEOLWON_STRING -> RESIDENCE_CITY_GANGWON_CHEOLWON
            RESIDENCE_CITY_GANGWON_CHUNCHEON_STRING -> RESIDENCE_CITY_GANGWON_CHUNCHEON
            RESIDENCE_CITY_GANGWON_TAEBAEK_STRING -> RESIDENCE_CITY_GANGWON_TAEBAEK
            RESIDENCE_CITY_GANGWON_PYEONGCHANG_STRING -> RESIDENCE_CITY_GANGWON_PYEONGCHANG
            RESIDENCE_CITY_GANGWON_HWACHEON_STRING -> RESIDENCE_CITY_GANGWON_HWACHEON
            RESIDENCE_CITY_GANGWON_HONGCHEON_STRING -> RESIDENCE_CITY_GANGWON_HONGCHEON
            RESIDENCE_CITY_GANGWON_HOENGSEONG_STRING -> RESIDENCE_CITY_GANGWON_HOENGSEONG

            RESIDENCE_CITY_GYEONGSANG_DAEGU_STRING -> RESIDENCE_CITY_GYEONGSANG_DAEGU
            RESIDENCE_CITY_GYEONGSANG_BUSAN_STRING -> RESIDENCE_CITY_GYEONGSANG_BUSAN
            RESIDENCE_CITY_GYEONGSANG_ULSAN_STRING -> RESIDENCE_CITY_GYEONGSANG_ULSAN
            RESIDENCE_CITY_GYEONGSANG_GYEONGSAN_STRING -> RESIDENCE_CITY_GYEONGSANG_GYEONGSAN
            RESIDENCE_CITY_GYEONGSANG_GYEONGJU_STRING -> RESIDENCE_CITY_GYEONGSANG_GYEONGJU
            RESIDENCE_CITY_GYEONGSANG_GEOJE_STRING -> RESIDENCE_CITY_GYEONGSANG_GEOJE
            RESIDENCE_CITY_GYEONGSANG_GUMI_STRING -> RESIDENCE_CITY_GYEONGSANG_GUMI
            RESIDENCE_CITY_GYEONGSANG_GIMHAE_STRING -> RESIDENCE_CITY_GYEONGSANG_GIMHAE
            RESIDENCE_CITY_GYEONGSANG_GIMCHEON_STRING -> RESIDENCE_CITY_GYEONGSANG_GIMCHEON
            RESIDENCE_CITY_GYEONGSANG_GEOCHANG_STRING -> RESIDENCE_CITY_GYEONGSANG_GEOCHANG
            RESIDENCE_CITY_GYEONGSANG_GORYEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_GORYEONG
            RESIDENCE_CITY_GYEONGSANG_GOSEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_GOSEONG
            RESIDENCE_CITY_GYEONGSANG_GUNWI_STRING -> RESIDENCE_CITY_GYEONGSANG_GUNWI
            RESIDENCE_CITY_GYEONGSANG_NAMHAE_STRING -> RESIDENCE_CITY_GYEONGSANG_NAMHAE
            RESIDENCE_CITY_GYEONGSANG_MUNGYEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_MUNGYEONG
            RESIDENCE_CITY_GYEONGSANG_MIRYANG_STRING -> RESIDENCE_CITY_GYEONGSANG_MIRYANG
            RESIDENCE_CITY_GYEONGSANG_BONGHWA_STRING -> RESIDENCE_CITY_GYEONGSANG_BONGHWA
            RESIDENCE_CITY_GYEONGSANG_SACHEON_STRING -> RESIDENCE_CITY_GYEONGSANG_SACHEON
            RESIDENCE_CITY_GYEONGSANG_SANCHEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_SANCHEONG
            RESIDENCE_CITY_GYEONGSANG_SANGJU_STRING -> RESIDENCE_CITY_GYEONGSANG_SANGJU
            RESIDENCE_CITY_GYEONGSANG_SEONGJU_STRING -> RESIDENCE_CITY_GYEONGSANG_SEONGJU
            RESIDENCE_CITY_GYEONGSANG_ANDONG_STRING -> RESIDENCE_CITY_GYEONGSANG_ANDONG
            RESIDENCE_CITY_GYEONGSANG_YEONGCHEON_STRING -> RESIDENCE_CITY_GYEONGSANG_YEONGCHEON
            RESIDENCE_CITY_GYEONGSANG_UISEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_UISEONG
            RESIDENCE_CITY_GYEONGSANG_YEONGJU_STRING -> RESIDENCE_CITY_GYEONGSANG_YEONGJU
            RESIDENCE_CITY_GYEONGSANG_YEONGYANG_STRING -> RESIDENCE_CITY_GYEONGSANG_YEONGYANG
            RESIDENCE_CITY_GYEONGSANG_YEONGDEOK_STRING -> RESIDENCE_CITY_GYEONGSANG_YEONGDEOK
            RESIDENCE_CITY_GYEONGSANG_YECHEON_STRING -> RESIDENCE_CITY_GYEONGSANG_YECHEON
            RESIDENCE_CITY_GYEONGSANG_ULJIN_STRING -> RESIDENCE_CITY_GYEONGSANG_ULJIN
            RESIDENCE_CITY_GYEONGSANG_ULLEUNG_STRING -> RESIDENCE_CITY_GYEONGSANG_ULLEUNG
            RESIDENCE_CITY_GYEONGSANG_YANGSAN_STRING -> RESIDENCE_CITY_GYEONGSANG_YANGSAN
            RESIDENCE_CITY_GYEONGSANG_UIRYEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_UIRYEONG
            RESIDENCE_CITY_GYEONGSANG_JINJU_STRING -> RESIDENCE_CITY_GYEONGSANG_JINJU
            RESIDENCE_CITY_GYEONGSANG_CHANGWON_STRING -> RESIDENCE_CITY_GYEONGSANG_CHANGWON
            RESIDENCE_CITY_GYEONGSANG_CHANGNYEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_CHANGNYEONG
            RESIDENCE_CITY_GYEONGSANG_CHEONGSONG_STRING -> RESIDENCE_CITY_GYEONGSANG_CHEONGSONG
            RESIDENCE_CITY_GYEONGSANG_CHEONGDO_STRING -> RESIDENCE_CITY_GYEONGSANG_CHEONGDO
            RESIDENCE_CITY_GYEONGSANG_CHILGOK_STRING -> RESIDENCE_CITY_GYEONGSANG_CHILGOK
            RESIDENCE_CITY_GYEONGSANG_TONGYEONG_STRING -> RESIDENCE_CITY_GYEONGSANG_TONGYEONG
            RESIDENCE_CITY_GYEONGSANG_POHANG_STRING -> RESIDENCE_CITY_GYEONGSANG_POHANG
            RESIDENCE_CITY_GYEONGSANG_HAPCHEON_STRING -> RESIDENCE_CITY_GYEONGSANG_HAPCHEON
            RESIDENCE_CITY_GYEONGSANG_HAMAN_STRING -> RESIDENCE_CITY_GYEONGSANG_HAMAN
            RESIDENCE_CITY_GYEONGSANG_HAMYANG_STRING -> RESIDENCE_CITY_GYEONGSANG_HAMYANG
            RESIDENCE_CITY_GYEONGSANG_HADONG_STRING -> RESIDENCE_CITY_GYEONGSANG_HADONG

            RESIDENCE_CITY_JEONRA_GWANGJU_STRING -> RESIDENCE_CITY_JEONRA_GWANGJU
            RESIDENCE_CITY_JEONRA_GOCHANG_STRING -> RESIDENCE_CITY_JEONRA_GOCHANG
            RESIDENCE_CITY_JEONRA_GOKSEONG_STRING -> RESIDENCE_CITY_JEONRA_GOKSEONG
            RESIDENCE_CITY_JEONRA_GOHEUNG_STRING -> RESIDENCE_CITY_JEONRA_GOHEUNG
            RESIDENCE_CITY_JEONRA_GURYE_STRING -> RESIDENCE_CITY_JEONRA_GURYE
            RESIDENCE_CITY_JEONRA_GANGJIN_STRING -> RESIDENCE_CITY_JEONRA_GANGJIN
            RESIDENCE_CITY_JEONRA_GUNSAN_STRING -> RESIDENCE_CITY_JEONRA_GUNSAN
            RESIDENCE_CITY_JEONRA_GIMJE_STRING -> RESIDENCE_CITY_JEONRA_GIMJE
            RESIDENCE_CITY_JEONRA_GWANGYANG_STRING -> RESIDENCE_CITY_JEONRA_GWANGYANG
            RESIDENCE_CITY_JEONRA_NAJU_STRING -> RESIDENCE_CITY_JEONRA_NAJU
            RESIDENCE_CITY_JEONRA_NAMWON_STRING -> RESIDENCE_CITY_JEONRA_NAMWON
            RESIDENCE_CITY_JEONRA_DAMYANG_STRING -> RESIDENCE_CITY_JEONRA_DAMYANG
            RESIDENCE_CITY_JEONRA_MOKPO_STRING -> RESIDENCE_CITY_JEONRA_MOKPO
            RESIDENCE_CITY_JEONRA_MUAN_STRING -> RESIDENCE_CITY_JEONRA_MUAN
            RESIDENCE_CITY_JEONRA_MUJU_STRING -> RESIDENCE_CITY_JEONRA_MUJU
            RESIDENCE_CITY_JEONRA_BOSEONG_STRING -> RESIDENCE_CITY_JEONRA_BOSEONG
            RESIDENCE_CITY_JEONRA_BUAN_STRING -> RESIDENCE_CITY_JEONRA_BUAN
            RESIDENCE_CITY_JEONRA_SHINAN_STRING -> RESIDENCE_CITY_JEONRA_SHINAN
            RESIDENCE_CITY_JEONRA_SUNCHEON_STRING -> RESIDENCE_CITY_JEONRA_SUNCHEON
            RESIDENCE_CITY_JEONRA_SUNCHANG_STRING -> RESIDENCE_CITY_JEONRA_SUNCHANG
            RESIDENCE_CITY_JEONRA_YEOSU_STRING -> RESIDENCE_CITY_JEONRA_YEOSU
            RESIDENCE_CITY_JEONRA_YEONGAM_STRING -> RESIDENCE_CITY_JEONRA_YEONGAM
            RESIDENCE_CITY_JEONRA_YEONGGWANG_STRING -> RESIDENCE_CITY_JEONRA_YEONGGWANG
            RESIDENCE_CITY_JEONRA_WANDO_STRING -> RESIDENCE_CITY_JEONRA_WANDO
            RESIDENCE_CITY_JEONRA_WANJU_STRING -> RESIDENCE_CITY_JEONRA_WANJU
            RESIDENCE_CITY_JEONRA_IKSAN_STRING -> RESIDENCE_CITY_JEONRA_IKSAN
            RESIDENCE_CITY_JEONRA_IMSIL_STRING -> RESIDENCE_CITY_JEONRA_IMSIL
            RESIDENCE_CITY_JEONRA_JANGSEONG_STRING -> RESIDENCE_CITY_JEONRA_JANGSEONG
            RESIDENCE_CITY_JEONRA_JANGSU_STRING -> RESIDENCE_CITY_JEONRA_JANGSU
            RESIDENCE_CITY_JEONRA_JEONGEUP_STRING -> RESIDENCE_CITY_JEONRA_JEONGEUP
            RESIDENCE_CITY_JEONRA_JEONJU_STRING -> RESIDENCE_CITY_JEONRA_JEONJU
            RESIDENCE_CITY_JEONRA_JINAN_STRING -> RESIDENCE_CITY_JEONRA_JINAN
            RESIDENCE_CITY_JEONRA_JINDO_STRING -> RESIDENCE_CITY_JEONRA_JINDO
            RESIDENCE_CITY_JEONRA_JANGHEUNG_STRING -> RESIDENCE_CITY_JEONRA_JANGHEUNG
            RESIDENCE_CITY_JEONRA_HWASUN_STRING -> RESIDENCE_CITY_JEONRA_HWASUN
            RESIDENCE_CITY_JEONRA_HAENAM_STRING -> RESIDENCE_CITY_JEONRA_HAENAM
            RESIDENCE_CITY_JEONRA_HAMPYEONG_STRING -> RESIDENCE_CITY_JEONRA_HAMPYEONG

            RESIDENCE_CITY_CHUNGCHEONG_DAEJEON_STRING -> RESIDENCE_CITY_CHUNGCHEONG_DAEJEON
            RESIDENCE_CITY_CHUNGCHEONG_SEJONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_SEJONG
            RESIDENCE_CITY_CHUNGCHEONG_GONGJU_STRING -> RESIDENCE_CITY_CHUNGCHEONG_GONGJU
            RESIDENCE_CITY_CHUNGCHEONG_GEUMSAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_GEUMSAN
            RESIDENCE_CITY_CHUNGCHEONG_GOESAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_GOESAN
            RESIDENCE_CITY_CHUNGCHEONG_GYERYONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_GYERYONG
            RESIDENCE_CITY_CHUNGCHEONG_NONSAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_NONSAN
            RESIDENCE_CITY_CHUNGCHEONG_DANGJIN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_DANGJIN
            RESIDENCE_CITY_CHUNGCHEONG_DANYANG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_DANYANG
            RESIDENCE_CITY_CHUNGCHEONG_BORYEONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_BORYEONG
            RESIDENCE_CITY_CHUNGCHEONG_BUYEO_STRING -> RESIDENCE_CITY_CHUNGCHEONG_BUYEO
            RESIDENCE_CITY_CHUNGCHEONG_BOEUN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_BOEUN
            RESIDENCE_CITY_CHUNGCHEONG_SEOSAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_SEOSAN
            RESIDENCE_CITY_CHUNGCHEONG_SEOCHEON_STRING -> RESIDENCE_CITY_CHUNGCHEONG_SEOCHEON
            RESIDENCE_CITY_CHUNGCHEONG_YEONGDONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_YEONGDONG
            RESIDENCE_CITY_CHUNGCHEONG_OKCHEON_STRING -> RESIDENCE_CITY_CHUNGCHEONG_OKCHEON
            RESIDENCE_CITY_CHUNGCHEONG_EUMSEONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_EUMSEONG
            RESIDENCE_CITY_CHUNGCHEONG_YESAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_YESAN
            RESIDENCE_CITY_CHUNGCHEONG_ASAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_ASAN
            RESIDENCE_CITY_CHUNGCHEONG_JECHEON_STRING -> RESIDENCE_CITY_CHUNGCHEONG_JECHEON
            RESIDENCE_CITY_CHUNGCHEONG_JEUNGPYEONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_JEUNGPYEONG
            RESIDENCE_CITY_CHUNGCHEONG_JINCHEON_STRING -> RESIDENCE_CITY_CHUNGCHEONG_JINCHEON
            RESIDENCE_CITY_CHUNGCHEONG_CHEONGJU_STRING -> RESIDENCE_CITY_CHUNGCHEONG_CHEONGJU
            RESIDENCE_CITY_CHUNGCHEONG_CHUNGJU_STRING -> RESIDENCE_CITY_CHUNGCHEONG_CHUNGJU
            RESIDENCE_CITY_CHUNGCHEONG_CHEONAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_CHEONAN
            RESIDENCE_CITY_CHUNGCHEONG_CHEONGYANG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_CHEONGYANG
            RESIDENCE_CITY_CHUNGCHEONG_TAEAN_STRING -> RESIDENCE_CITY_CHUNGCHEONG_TAEAN
            RESIDENCE_CITY_CHUNGCHEONG_HONGSEONG_STRING -> RESIDENCE_CITY_CHUNGCHEONG_HONGSEONG

            RESIDENCE_CITY_JEJU_JEJU_STRING -> RESIDENCE_CITY_JEJU_JEJU
            RESIDENCE_CITY_JEJU_SEOGWIPO_STRING -> RESIDENCE_CITY_JEJU_SEOGWIPO

            else -> RESIDENCE_CITY_UNKNOWN
        }
    }

    fun academicBackgroundValueOf(academicBackground: String): Int {
        return when(academicBackground) {
            ACADEMIC_BACKGROUND_GRADUATED_UNDER_ELEMENTARY_SCHOOL_STRING -> ACADEMIC_BACKGROUND_GRADUATED_UNDER_ELEMENTARY_SCHOOL
            ACADEMIC_BACKGROUND_GRADUATED_UNDER_MIDDLE_SCHOOL_STRING -> ACADEMIC_BACKGROUND_GRADUATED_UNDER_MIDDLE_SCHOOL
            ACADEMIC_BACKGROUND_GRADUATED_UNDER_HIGH_SCHOOL_STRING -> ACADEMIC_BACKGROUND_GRADUATED_UNDER_HIGH_SCHOOL
            ACADEMIC_BACKGROUND_GRADUATED_UNDER_GRAD_SCHOOL_STRING -> ACADEMIC_BACKGROUND_GRADUATED_UNDER_GRAD_SCHOOL
            else -> ACADEMIC_BACKGROUND_UNKNOWN
        }
    }

    fun healthConditionValueOf(healthCondition: String): Int {
        return when(healthCondition) {
            HEALTH_CONDITION_CLEAR_STRING -> HEALTH_CONDITION_CLEAR
            HEALTH_CONDITION_LOSS_OF_TEETH_STRING -> HEALTH_CONDITION_LOSS_OF_TEETH
            HEALTH_CONDITION_ARTICULATION_DISORDER_STRING -> HEALTH_CONDITION_ARTICULATION_DISORDER
            HEALTH_CONDITION_BOTH_STRING -> HEALTH_CONDITION_BOTH
            else -> HEALTH_CONDITION_UNKNOWN
        }
    }
}